<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <AssemblyName>MouseNavigator_WPF</AssemblyName>
    <RootNamespace>MouseNavigator_WPF</RootNamespace>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.User32" Version="5.0.0" />
  </ItemGroup>
</Project>
