<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>MouseNavigator_WPF</AssemblyName>
    <RootNamespace>MouseNavigator_WPF</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InputSimulator" Version="1.0.4" />
  </ItemGroup>

</Project>